### ISSUE TITLE
Webpack 4 support?

### ISSUE THREAD

**Issue by boris-jarkowicz** [markdalgleish/static-site-generator-webpack-plugin#123] opened 2018-03-16 12:29 UTC
Hi there,

i'm currently upgrading to webpack 4 and i'm using the `static-site-generator-webpack-plugin` for my build. It currently errors with the following output:

```
ERROR in SyntaxError: Unexpected token .
    at module.exports (/Users/anon/gitrepos/myproject/node_modules/eval/eval.js:68:18)
    at /Users/anon/gitrepos/myproject/node_modules/static-site-generator-webpack-plugin/index.js:42:22
```
I'm not really sure if it has anything to do with your plugin, but the stacktrace points to `eval`, one dependency of this plugin.

Maybe it has to do something with the way webpack 4 handles `module.exports`?

Any help would be appreciated :)

**Comment by jahredhope** [comment] 2018-03-26 08:04
I've previously used this module with Webpack 4 and don't believe I had this issue.
Is this a reproducible scenario?
Were you able to find a solution?

**Comment by boris-jarkowicz** [comment] 2018-03-26 12:21
I haven't had the time to debug the issue properly, as i'm not really sure what's wrong, that is because i was very careful with finding the cause to the thrown error. Did you also move from `extract-text-webpack-plugin` to `mini-css-extract-plugin`?

**Comment by jahredhope** [comment] 2018-03-26 21:15
I used the beta release of extract text plugin at the time. And since then have been using css-in-js so haven't needed either.
Which were you using when you got the error?

**Comment by boris-jarkowicz** [comment] 2018-03-29 13:36
i was wrong to assume that this error is caused by this plugin, i had a wrong configuration of my css and sass loaders, the error is gone and now i have another one, but that is a different story.

Thanks for your response @jahredhope

**Comment by richsilv** [comment] 2018-04-12 16:01
For what it's worth, I believe there's a problem when using this with the new [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin).

It seems to assume that the main bundle to evaluate in each chunk [will be the first entry in the array](https://github.com/markdalgleish/static-site-generator-webpack-plugin/blob/master/index.js#L148-L149) where there are multiple files per chunk, as there would be using that plugin. Unfortunately, this isn't the case, as the output is of the form `["chunkName.css", "chunkName.js"]`, which leaves the static-site-generator plugin trying to evaluate the CSS.

Would a simple `Array.find` to pull out the javascript filename in this case be a satisfactory fix? Happy to PR if so.

**Comment by boris-jarkowicz** [comment] 2018-04-19 12:02
would be worth a try, i ended up being stuck on the following errors, thrown on `stats: verbose` only.
Error message:
`ModuleConcatenation bailout: Module is not an ECMAScript module single entry`

Initially i thought this happens due to a conflict between `babel` and `webpack`, but adding `modules: false` to `.babelrc` didn't solve the issue. The page builds and runs without any further errors in the browser.

**Comment by Mydayyy** [comment] 2018-05-16 12:45
Any updates on this one? We´re currently running into this issue with our main chunk which has a css file as its first item. Has development on this plugin ceased?

**Comment by Ambroos** [comment] 2018-05-16 13:41
@Mydayyy You can use the package directly from my pull request temporarily, it'll stay available.

```bash
yarn add --dev static-site-generator-webpack-plugin@medialaan/static-site-generator-webpack-plugin#58524c0

# or

npm install --save-dev static-site-generator-webpack-plugin@medialaan/static-site-generator-webpack-plugin#58524c0
```

**Comment by jahredhope** [comment] 2018-11-19 23:31
Closed by https://github.com/markdalgleish/static-site-generator-webpack-plugin/pull/139

**Closed by jahredhope** 2018-11-19 23:31 UTC
